allow-greeting-message: true

chance-copper-ore: 15
chance-lapis-ore: 15
chance-coal-ore: 20
chance-redstone-ore: 20
chance-iron-ore: 30
chance-gold-ore: 30
chance-diamond-ore: 50
chance-emerald-ore: 60
chance-ancient-debris: 60

chance-spider-kill: 25
chance-zombie-kill: 30
chance-skeleton-kill: 30
chance-creeper-kill: 40
chance-enderman-kill: 60

kaucyjna-name: "&6Butelka kaucyjna"
kaucyjna-lore: "&fButelka, którą można wymienić klikając &7Shift + PPM&f."
disable-kaucyjna-lore: false
kaucyjna-with-infinity: true

use-vault-if-possible: true
exchange-material: "gold_nugget"

# exchange-no-amount: if economy is not set up on this server.
# exchange-yes-amount: if economy is set up on this server.
exchange-no-amount: 1
exchange-yes-amount: 0.5

# messages

message-could-not-exchange: "&cNie można było wymienić butelek kaucyjnych! Skontaktuj się z administratorem."
message-greeting-first: "&aWitaj na serwerze!"
message-greeting-second: "&aZbieraj &bbutelki kaucyjne &akopiąc i zabijając!"
message-kaucja-from-this-block: "&aZdobyłeś kaucję z tego bloku!"
message-kaucja-from-this-mob: "&aZdobyłeś kaucję z tego moba!"
message-kaucja-successfully-given: "&aPomyślnie nadano butelkę kaucyjną!"
message-player-is-offline: "&cTen gracz jest offline!"
message-successfully-config-reloaded: "&aPomyślnie zreloadowano config!"
message-unsufficient-permissions: "&cNie masz wystarczających permisji by to zrobić!"
message-wrong-args-nadaj: "&cPoprawne użycie: &f/nadaj <gracz> <ilość>&c!"

message-can-economy-work: "&bCzy butelki kaucyjne mogą działać na ekonomii: [(toggle)]" # [(toggle)]
message-is-economy-on: "&bCzy butelki kaucyjne aktualnie działają na ekonomii: [(toggle)]" # [(toggle)]
message-kaucja-successfully-granted: "&aPomyślnie nadano &b[(amount)] &abutelek kaucyjnych!" # [(amount)]
message-unknown-panel-option: "&cNieznana opcja! Opcje: &b([(options)])&c!" # [(options)]
message-successfully-exchanged-vault: "&aZamieniłeś butelki kaucyjne na &6[(money)]$!" # [(money)]
message-successfully-exchanged-item: "&aZamieniłeś butelki kaucyjne na &6[(amount)] &azłotych monetek!" # [(amount)]

message-yes: "&aTak"
message-no: "&cNie"