allow-greeting-message: true

chance-copper-ore: 15
chance-lapis-ore: 15
chance-coal-ore: 20
chance-redstone-ore: 20
chance-iron-ore: 30
chance-gold-ore: 30
chance-diamond-ore: 50
chance-emerald-ore: 60
chance-ancient-debris: 60

chance-spider-kill: 25
chance-zombie-kill: 30
chance-skeleton-kill: 30
chance-creeper-kill: 40
chance-enderman-kill: 60

kaucyjna-name: "&6Butelka kaucyjna"
kaucyjna-lore: "&fButelka, którą można wymienić klikając &7Shift + PPM&f."
disable-kaucyjna-lore: false
kaucyjna-with-infinity: true

exchange-material: "gold_nugget"
exchange-amount: 1