name: "ButelkaKaucyjna"
version: "1.0"
main: xyz.playboy.ButelkiKaucyjne
author: "WhitePlayboy69"
description: "Plugin który dodaje butelki kaucyjne"
api-version: '1.20'

commands:
  informacje:
    description: "Daje ci informacje o pluginie"
    usage: /informacje
  nadaj:
    description: "Nadaje tobie/komuś butelkę kaucyjną"
    usage: /nadaj <gracz> <ilość>
  panel:
    description: "Pozwala operować na pluginie"
    usage: /panel <opcja>

permissions:
  butelki.nadaj:
    description: "Pozwala ci nadać butelkę kaucyjną"
    default: op
  butelki.panel.reload:
    description: "Pozwala ci reloadować config pluginu"
    default: op
  butelki.panel.check-vault:
    description: "Pozwala ci sprawdzić czy butelki kaucyjne działają na zasaach ekonomii"
    default: op
  butelki.panel.help:
    description: "Pozwala ci sprawdzić pomoc o butelkach kaucyjnych"
    default: true

  butelki.panel.*:
    description: "Pozwala ci wypisać wszystkie opcje z /panel"
    default: op
    children:
      butelki.panel.reload: true
      butelki.panel.check-vault: true
      butelki.panel.help: true

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true

# Jak cos wczesniej ten plik sie nazywal paper-plugin.yml
# Ale nie dzialaja mi komendy jak jest ta nazwa wiec daje plugin.yml
# A pisali na papermc ze trzeba dac plugin.yml by to dzialalo wiec tak daje